# Default initial positions for kuka_kr6r900sixx's ros2_control fake system

initial_positions:
  joint_a1: 0.0
  joint_a2: 0.0
  joint_a3: 0.0
  joint_a4: 0.0
  joint_a5: 0.0
  joint_a6: 0.0
  wsg_50_base_joint_gripper_left: -0.04
  wsg_50_base_joint_gripper_right: 0.04