/**:
  ros__parameters:
    robot_description_planning:
      joint_limits:
        joint_a1:
          has_velocity_limits: true
          max_velocity: 3.14
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint_a2:
          has_velocity_limits: true
          max_velocity: 2.62
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint_a3:
          has_velocity_limits: true
          max_velocity: 3.14
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint_a4:
          has_velocity_limits: true
          max_velocity: 3.32
          has_acceleration_limits: true
          max_acceleration: 6.0
        joint_a5:
          has_velocity_limits: true
          max_velocity: 3.39
          has_acceleration_limits: true
          max_acceleration: 6.0
        joint_a6:
          has_velocity_limits: true
          max_velocity: 5.37
          has_acceleration_limits: true
          max_acceleration: 8.0
